### ISSUE TITLE
Scrying Lens -10 effect didn't reduce search value to 0 for activated artifact

### ISSUE THREAD

**Issue by joshtriplett** [Introscopia/Introscopia.github.io#1]
(Not sure if this is the right place to report a bug on Utopia Engine; if it isn't, please let me know.)

I obtained the Scrying Lens first. Since that should give up to -10 on searches in Glassrock Canyon, I went there next. The search turned up 113 - 111 = 2, which the Scrying Lens should have reduced to 0 for a perfect search and an activated artifact. However, the Golden Chassis turned up un-activated.

**Comment by Introscopia** [comment]
Artifacts need to be activated for their passives to kick in

**Comment by joshtriplett** [comment]
Ah, that makes sense. Sorry for the confusion.

**Comment by Introscopia** [comment]
no problem!
